apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-rakshith
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 64320003/nodejs-demo:latest
          ports:
            - containerPort: 8080
