apiVersion: v1
kind: Service
metadata:
  name: url-rakshith
spec:
  selector:
    app: node-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
      nodePort: 31110
